In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# Using Matrix multiplication for past averaging

In [4]:
torch.manual_seed(42)

a = torch.tril(torch.ones((3,3)))

a = a / torch.sum(a,1,keepdim=True)

b = torch.randint(0,10,(3,2)).float()
c = a @ b

print(a)
print(b)
print(c)

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])
